<?php

declare(strict_types=1);

namespace Swoole;

use Swoole\Coroutine\Socket;

/**
 * A Process object represents a child process to be forked from the current process. The class wraps process
 * creation with built-in inter-process communication (a pipe, and optionally a System V message queue), and also
 * provides static helpers for signal handling, process control, and daemonization.
 *
 * Objects of this class can be used in PHP CLI mode only.
 *
 * @not-serializable Objects of this class cannot be serialized.
 */
class Process
{
    /**
     * Flag that can be combined (through a bitwise OR) with the message queue mode passed to method
     * \Swoole\Process::useQueue() to make the message queue non-blocking: methods \Swoole\Process::push() and
     * \Swoole\Process::pop() return false immediately instead of blocking when the queue is full or empty.
     *
     * @see \Swoole\Process::useQueue()
     */
    public const IPC_NOWAIT = 256;

    /**
     * Option for method \Swoole\Process::close(): close the master end of the pipe, which is the end used by the
     * process where the Process object is created.
     *
     * @see \Swoole\Process::close()
     */
    public const PIPE_MASTER = 1;

    /**
     * Option for method \Swoole\Process::close(): close the worker end of the pipe, which is the end used by the
     * child process.
     *
     * @see \Swoole\Process::close()
     */
    public const PIPE_WORKER = 2;

    /**
     * Option for method \Swoole\Process::close(): shut down the reading direction of the pipe used by the current
     * process, keeping the pipe itself open.
     *
     * @see \Swoole\Process::close()
     */
    public const PIPE_READ = 3;

    /**
     * Option for method \Swoole\Process::close(): shut down the writing direction of the pipe used by the current
     * process, keeping the pipe itself open.
     *
     * @see \Swoole\Process::close()
     */
    public const PIPE_WRITE = 4;

    /**
     * Option for the $pipe_type parameter of the constructor: create the process without a pipe, so the two processes
     * have no built-in channel to exchange data through.
     *
     * @see \Swoole\Process::__construct()
     * @since 6.1.0
     */
    public const PIPE_TYPE_NONE = 0;

    /**
     * Option for the $pipe_type parameter of the constructor: use a stream typed pipe, i.e., a pair of connected
     * SOCK_STREAM Unix domain sockets. Data written into it arrives as a continuous stream of bytes with no message
     * boundaries, so the reading side may have to piece messages back together itself.
     *
     * @see \Swoole\Process::__construct()
     * @since 6.1.0
     */
    public const PIPE_TYPE_STREAM = 1;

    /**
     * Option for the $pipe_type parameter of the constructor: use a datagram typed pipe, i.e., a pair of connected
     * SOCK_DGRAM Unix domain sockets. Each write is delivered as one self-contained message, so the reading side gets
     * back exactly what was written, one message per read.
     *
     * @see \Swoole\Process::__construct()
     * @since 6.1.0
     */
    public const PIPE_TYPE_DGRAM = 2;

    /**
     * The file descriptor of the process's own end of the pipe used to exchange data with the other side. It holds the
     * master end's descriptor in the process where the object is created, and the worker end's descriptor inside the
     * child process.
     *
     * It's only set when the process has a pipe (which is the case by default; see the $pipe_type parameter of the
     * constructor): the property is set to the master end's descriptor when the object is constructed, and it's
     * updated to the worker end's descriptor inside the child process once method \Swoole\Process::start() forks it.
     * It stays NULL when the process is created without a pipe.
     *
     * @readonly
     * @see \Swoole\Process::__construct()
     * @see \Swoole\Process::start()
     * @see \Swoole\Process::exportSocket()
     */
    public ?int $pipe = null;

    /**
     * Identifier of the System V message queue used by the process, as returned by system call msgget().
     *
     * It's only set when method \Swoole\Process::useQueue() is called successfully.
     *
     * @readonly
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Process::$msgQueueKey
     * @see https://www.man7.org/linux/man-pages/man2/msgget.2.html
     */
    public ?int $msgQueueId = null;

    /**
     * Key of the System V message queue used by the process, which is parameter $key passed to method
     * \Swoole\Process::useQueue(). When 0 or a negative integer is passed, the key generated by calling system call
     * ftok() on the PHP file where method \Swoole\Process::useQueue() is called is used instead; the "proj_id"
     * argument of ftok() (see ftok(3) below) is hardcoded to 1 in Swoole.
     *
     * It's only set when method \Swoole\Process::useQueue() is called successfully.
     *
     * @readonly
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Process::$msgQueueId
     * @see https://www.man7.org/linux/man-pages/man3/ftok.3.html
     */
    public ?int $msgQueueKey = null;

    /**
     * Process ID. This is to uniquely identify the process in the OS.
     *
     * It's NULL until the process represented by the object exists:
     *   - After method \Swoole\Process::start() is called successfully, it holds the process ID of the child process
     *     created, both in the parent process and in the child process itself.
     *   - For a process added to a server through method \Swoole\Server::addProcess(), it's set inside the user process
     *     itself when the process starts; it's not set in the process where method \Swoole\Server::addProcess() is
     *     called.
     *   - For an object returned by method \Swoole\Process\Pool::getProcess(), it holds the process ID of the
     *     corresponding worker process in the process pool.
     *
     * @readonly
     * @see \Swoole\Process::start()
     * @see \Swoole\Server::addProcess()
     * @see \Swoole\Process\Pool::getProcess()
     */
    public ?int $pid = null;

    /**
     * ID of the process.
     *
     * Unless one of the special cases described below applies, the ID is not coordinated across the running Swoole
     * program. It comes from a counter kept by (and private to) the PHP process in which the \Swoole\Process object is
     * created: the first object created in that process gets ID 1, and every object created afterwards gets the
     * previous ID plus one. If a \Swoole\Server has already been started in the current process by the time the first
     * \Swoole\Process object is created there, the counter starts from the total number of workers of the server (event
     * worker processes + task worker processes + user processes) instead of 1, so that the IDs don't clash with the IDs
     * of the server's own workers.
     *
     * The ID is assigned differently in the following cases:
     *   - When the object is created inside a worker thread of a running multi-threaded server (SWOOLE_THREAD mode), it
     *     represents one of the user processes of that server instead of a newly created process, and it takes the ID
     *     of that user process as is.
     *   - When the object is passed to method \Swoole\Server::addProcess(), that method overwrites the ID with the
     *     index of the user process among all the user processes added to the server (0 for the first one). Later on,
     *     when the server starts the user process, the ID is overwritten again, inside the user process, with the ID of
     *     the corresponding worker of the server (event worker processes and task worker processes counted in).
     *   - When the object comes from method \Swoole\Process\Pool::getProcess(), the ID is the ID of the worker process
     *     calling the method, which is not necessarily the ID of the worker process that the object represents.
     *
     * Therefore, the ID can be 0, e.g., right after an object is added to a server as the server's first user process,
     * or in the first worker process of a process pool.
     *
     * Besides identifying the process, the ID also determines the message type used by methods \Swoole\Process::push()
     * and \Swoole\Process::pop().
     *
     * Please note that although a process created directly in PHP (through "new \Swoole\Process(...)" followed by a
     * method call to \Swoole\Process::start()) has an ID internally, assigned as described above, this property is not
     * populated for it: the property stays NULL, and the internal ID is only observable indirectly (e.g., through the
     * message type used by methods \Swoole\Process::push() and \Swoole\Process::pop()). The property is populated only
     * in the \Swoole\Server::addProcess() and \Swoole\Process\Pool::getProcess() cases described above.
     *
     * @readonly
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Server::addProcess()
     * @see \Swoole\Process\Pool::getProcess()
     */
    public ?int $id = null;

    /**
     * @var callable The callback function of the process.
     */
    private $callback;

    /**
     * The constructor.
     *
     * The object represents a child process to be forked by method \Swoole\Process::start(); the callback function
     * given is what the child process executes.
     *
     * Objects of this class can be created in PHP CLI mode only.
     *
     * @param callable $callback The callback function of the process. It's called inside the child process, with the
     *                           \Swoole\Process object as its only argument, once the child process is started; the
     *                           child process quits when the callback function finishes.
     * @param bool $redirect_stdin_and_stdout Redirect the standard input, output, and error of the child process to
     *                                        the pipe: data written by the child process to STDOUT or STDERR can then
     *                                        be read from the pipe (e.g., via method \Swoole\Process::read()) on the
     *                                        other side, and data written into the pipe on the other side can be read
     *                                        by the child process from STDIN. When enabled, a stream typed pipe is
     *                                        used implicitly, overriding parameter $pipe_type.
     * @param int $pipe_type Type of the pipe created for exchanging data between the current process and the child
     *                       process. Since Swoole 6.1.0 there are named constants for the three accepted values:
     *                       \Swoole\Process::PIPE_TYPE_NONE (0, no pipe is created),
     *                       \Swoole\Process::PIPE_TYPE_STREAM (1, a pair of connected SOCK_STREAM Unix domain
     *                       sockets), and \Swoole\Process::PIPE_TYPE_DGRAM (2, a pair of connected SOCK_DGRAM Unix
     *                       domain sockets). The default value is declared as constant SOCK_DGRAM, whose value (2 on
     *                       Linux and macOS) matches the numbering of the pipe types.
     * @param bool $enable_coroutine Enable coroutine support in the child process or not. When enabled, an event loop
     *                               is created in the child process and the callback function runs inside a
     *                               coroutine; the child process quits once the callback function has returned and
     *                               the event loop has nothing left to process.
     * @throws \Error When the constructor is called more than once on the same object, when used not in PHP CLI mode,
     *                when called in the master process of a running server, or when asynchronous (AIO) threads have
     *                been started in the current process.
     * @throws \Swoole\Exception When failed to create the Unix domain sockets backing the pipe.
     * @see \Swoole\Process::start()
     * @see \Swoole\Process::set()
     * @see \Swoole\Process::$pipe
     */
    public function __construct(callable $callback, bool $redirect_stdin_and_stdout = false, int $pipe_type = SOCK_DGRAM, bool $enable_coroutine = false)
    {
    }

    /**
     * The destructor.
     *
     * There is no need to call this method directly. The resources held by the object (the pipe, for example) are
     * released internally when the object is destroyed.
     */
    public function __destruct()
    {
    }

    /**
     * Set process scheduling priority.
     *
     * Parameter $who is added in Swoole 5.0.2. Prior to this version, this method can only be used to set the priority
     * of the current process through method call $this->setPriority(PRIO_PROCESS, $priority).
     *
     * @param int $which One of the following three constants:
     *                   - PRIO_PROCESS: Set the priority of the process specified.
     *                   - PRIO_PGRP: Set the priority of all the processes in the process group specified.
     *                   - PRIO_USER: Set the priority of all the processes owned by the user specified.
     * @param int $priority The priority value. Lower priorities cause more favorable scheduling. The actual priority
     *                      range varies between systems. On Linux 1.3.43+, it's in the range -20 to 19.
     * @param int|null $who Interpreted relative to $which:
     *                      - PRIO_PROCESS: A process identifier.
     *                      - PRIO_PGRP: Process group identifier.
     *                      - PRIO_USER: An effective user ID.
     *                      This parameter can be ignored (or set to NULL) when $which is PRIO_PROCESS and $who
     *                      is $this->pid. In another word, the following two calls are equivalent:
     *                      - $this->setPriority(PRIO_PROCESS, $priority, $this->pid);
     *                      - $this->setPriority(PRIO_PROCESS, $priority);
     * @return bool Returns true on success or false on failure.
     * @see \Swoole\Process::getPriority()
     */
    public function setPriority(int $which, int $priority, ?int $who = null): bool
    {
    }

    /**
     * Get process scheduling priority.
     *
     * Parameter $who is added in Swoole 5.0.2. Prior to this version, this method can only be used to get the priority
     * of the current process through method call $this->getPriority(PRIO_PROCESS).
     *
     * @param int $which One of the three constants: PRIO_PROCESS, PRIO_PGRP, or PRIO_USER.
     * @param int|null $who Interpreted relative to $which:
     *                      - PRIO_PROCESS: A process identifier.
     *                      - PRIO_PGRP: Process group identifier.
     *                      - PRIO_USER: An effective user ID.
     *                      This parameter can be ignored (or set to NULL) when $which is PRIO_PROCESS and $who is
     *                      $this->pid. In another word, the following two calls are equivalent:
     *                      - $this->getPriority(PRIO_PROCESS, $this->pid);
     *                      - $this->getPriority(PRIO_PROCESS);
     * @return int|false The highest priority (lowest numerical value) enjoyed by any of the specified processes, or false on error.
     * @see \Swoole\Process::setPriority()
     */
    public function getPriority(int $which, ?int $who = null): int|false
    {
    }

    /**
     * Configure the process.
     *
     * @param array $settings Only one setting is supported: "enable_coroutine" (bool), which overrides parameter
     *                        $enable_coroutine passed to the constructor. It must be set before method
     *                        \Swoole\Process::start() is called. Any other element in the array is ignored silently.
     * @see \Swoole\Process::__construct()
     */
    public function set(array $settings): void
    {
    }

    /**
     * Set the read and write timeout on the pipe of the process.
     *
     * @param float $seconds The timeout in seconds. When 0 is passed, the timeout is disabled, which means read and
     *                       write operations on the pipe block until they are done.
     * @return bool Returns true on success or false on failure. It also returns false, with an E_WARNING level error
     *              thrown out, when the process doesn't have a pipe.
     * @see \Swoole\Process::setBlocking()
     */
    public function setTimeout(float $seconds): bool
    {
    }

    /**
     * Set the pipe of the process to blocking or non-blocking mode.
     *
     * By default the pipe is in blocking mode: read and write operations on it wait until data arrives or until the
     * data is written out. In non-blocking mode, methods \Swoole\Process::read() and \Swoole\Process::write() return
     * false right away when there is no data to read or when the data can't be written out at once.
     *
     * An E_WARNING level error is thrown out when the process doesn't have a pipe.
     *
     * The signature of this method changed in Swoole 6.1.0:
     *   - before: public function setBlocking(bool $blocking): void
     *   - now:    public function setBlocking(bool $blocking): bool
     *
     * @param bool $blocking Put the pipe in blocking mode (true) or non-blocking mode (false).
     * @return bool Returns true on success or false on failure. It also returns false, with an E_WARNING level error
     *              thrown out, when the process doesn't have a pipe.
     * @see \Swoole\Process::setTimeout()
     * @see \Swoole\Process::read()
     * @see \Swoole\Process::write()
     */
    public function setBlocking(bool $blocking): bool
    {
    }

    /**
     * Create (or get access to) a System V message queue, and use it to exchange data between the process and the
     * process where the Process object is created.
     *
     * Once this method is called successfully, properties $msgQueueId and $msgQueueKey are set accordingly.
     *
     * Every message in a System V message queue carries a positive integer called the message type (the "mtype" field
     * of the message passed to system call msgsnd(), and the "msgtyp" argument of system call msgrcv()), which allows a
     * reader to fetch messages selectively. Swoole uses ($this->id + 1) as the message type of the process; 1 is added
     * because a message type must be greater than 0, while $this->id can be 0.
     *
     * There are two modes of the message queue:
     *   - SWOOLE_MSGQUEUE_ORIENT (1): Method \Swoole\Process::pop() passes ($this->id + 1) as the "msgtyp" argument of
     *     system call msgrcv(), and thus only fetches messages of that message type from the queue.
     *   - SWOOLE_MSGQUEUE_BALANCE (2, the default): Method \Swoole\Process::pop() passes 0 as the "msgtyp" argument of
     *     system call msgrcv(), and thus fetches the first message in the queue, no matter what message type it is of.
     *
     * Either mode can be combined with constant \Swoole\Process::IPC_NOWAIT (256), e.g.,
     * SWOOLE_MSGQUEUE_BALANCE | \Swoole\Process::IPC_NOWAIT, to make the queue non-blocking. In that case, methods
     * \Swoole\Process::push() and \Swoole\Process::pop() return false immediately instead of blocking, when the queue
     * is full or empty.
     *
     * Please note that no matter which mode is used, messages pushed through method \Swoole\Process::push() always
     * carry message type ($this->id + 1).
     *
     * @param int $key Key of the message queue, which is passed to system call msgget() together with flag IPC_CREAT
     *                 and permissions 0666. When 0 or a negative integer is passed, the key generated by calling
     *                 system call ftok() on the PHP file where this method is called is used instead; the "proj_id"
     *                 argument of ftok() (see ftok(3) below) is hardcoded to 1 in Swoole.
     * @param int $mode Mode of the message queue, as described above.
     * @param int $capacity Maximum number of bytes allowed in the message queue (msg_qbytes). The system default is
     *                      used when a non-positive integer is passed.
     * @return bool Returns true on success or false on failure.
     * @see \Swoole\Process::$msgQueueId
     * @see \Swoole\Process::$msgQueueKey
     * @see \Swoole\Process::push()
     * @see \Swoole\Process::pop()
     * @see \Swoole\Process::statQueue()
     * @see \Swoole\Process::freeQueue()
     * @see https://www.man7.org/linux/man-pages/man3/ftok.3.html
     * @see https://www.man7.org/linux/man-pages/man2/msgget.2.html
     * @see https://www.man7.org/linux/man-pages/man2/msgsnd.2.html
     * @see https://www.man7.org/linux/man-pages/man2/msgrcv.2.html
     */
    public function useQueue(int $key = 0, int $mode = 2, int $capacity = -1): bool
    {
    }

    /**
     * Get statistics of the message queue used by the process.
     *
     * @return array{queue_num: int, queue_bytes: int}|false Returns an array containing the number of messages
     *                                                       currently in the queue ("queue_num") and the number of
     *                                                       bytes currently in the queue ("queue_bytes"); returns
     *                                                       false on failure.
     * @see \Swoole\Process::useQueue()
     */
    public function statQueue(): array|false
    {
    }

    /**
     * Destroy the message queue used by the process, and release all the resources (messages included) associated
     * with it.
     *
     * @return bool Returns true on success or false on failure.
     * @see \Swoole\Process::useQueue()
     */
    public function freeQueue(): bool
    {
    }

    /**
     * Fork the child process and start it.
     *
     * The child process executes the callback function passed to the constructor and quits when the function
     * finishes; the child process itself never returns from this method call. In the calling process, the method
     * returns the process ID of the child process.
     *
     * @return bool|int Returns the process ID of the child process (a positive integer) on success. It returns
     *                  false, with an E_WARNING level error thrown out, when the process has been started already
     *                  (and is still alive), or when the operating system fails to fork a new process.
     * @see \Swoole\Process::__construct()
     * @see \Swoole\Process::wait()
     * @see \Swoole\Process::$pid
     */
    public function start(): bool|int
    {
    }

    /**
     * Write data into the pipe of the process, to be read on the other end.
     *
     * This method can be used both in the process where the object is created and in the child process, each writing
     * to its own end of the pipe. When an event loop is running in the current process and the pipe is in
     * non-blocking mode, the data is written asynchronously through the event loop; otherwise, the method blocks
     * until the data is written out.
     *
     * @param string $data The data to write. It can't be empty.
     * @return int|false Returns the number of bytes written on success. It returns false, with an E_WARNING level
     *                   error thrown out, when $data is empty, when the process doesn't have a pipe, or when the
     *                   write fails.
     * @see \Swoole\Process::read()
     * @see \Swoole\Process::setBlocking()
     */
    public function write(string $data): int|false
    {
    }

    /**
     * Close the pipe of the process, or shut down one direction of it.
     *
     * Parameter $which takes one of the following values:
     *   - \Swoole\Process::PIPE_READ (3): Shut down the reading direction of the pipe used by the current process,
     *     through system call shutdown(fd, SHUT_RD). The pipe itself is kept open.
     *   - \Swoole\Process::PIPE_WRITE (4): Shut down the writing direction of the pipe used by the current process,
     *     through system call shutdown(fd, SHUT_WR). The pipe itself is kept open.
     *   - \Swoole\Process::PIPE_MASTER (1): Close the master end of the pipe, which is the end used by the process
     *     where the Process object is created.
     *   - \Swoole\Process::PIPE_WORKER (2): Close the worker end of the pipe, which is the end used by the child
     *     process.
     *   - 0 (the default): Close both ends of the pipe and destroy the pipe.
     *
     * @param int $which One of the values described above.
     * @return bool Returns true on success or false on failure. It also returns false, with an E_WARNING level error
     *              thrown out, when the process doesn't have a pipe (or when the pipe has been destroyed already).
     * @see \Swoole\Process::exportSocket()
     */
    public function close(int $which = 0): bool
    {
    }

    /**
     * Read data from the pipe of the process.
     *
     * This method can be used both in the process where the object is created and in the child process, each reading
     * from its own end of the pipe. By default the method blocks until data is available.
     *
     * @param int $size Maximum number of bytes to read.
     * @return string|false Returns the data read on success; returns false on failure, with an E_WARNING level error
     *                      thrown out when the process doesn't have a pipe or when the read fails (unless the read
     *                      was interrupted by a signal).
     * @see \Swoole\Process::write()
     * @see \Swoole\Process::setBlocking()
     * @see \Swoole\Process::setTimeout()
     */
    public function read(int $size = 8192): string|false
    {
    }

    /**
     * Push data into the message queue created by method \Swoole\Process::useQueue().
     *
     * No matter which mode the queue is in, the message is always pushed with message type ($this->id + 1), i.e., the
     * "mtype" field of the message passed to system call msgsnd() is set to ($this->id + 1).
     *
     * @param string $data The data to push. It can't be empty, and its length must be less than 65536 bytes;
     *                     otherwise, false is returned with an E_WARNING level error thrown out.
     * @return bool Returns true on success or false on failure. It also returns false, with an E_WARNING level error
     *              thrown out, when method \Swoole\Process::useQueue() hasn't been called successfully beforehand.
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Process::pop()
     * @see \Swoole\Process::$id
     * @see https://www.man7.org/linux/man-pages/man2/msgsnd.2.html
     */
    public function push(string $data): bool
    {
    }

    /**
     * Fetch data from the message queue created by method \Swoole\Process::useQueue().
     *
     * Which message is fetched depends on the mode of the queue: in mode SWOOLE_MSGQUEUE_ORIENT, only messages of
     * message type ($this->id + 1) are fetched; in mode SWOOLE_MSGQUEUE_BALANCE (the default), the first message in the
     * queue is fetched, no matter what message type it is of.
     *
     * @param int $size Maximum number of bytes to read. When the value passed in is not in the range of 1 to 65536, it
     *                  is reset to 65536 implicitly.
     * @return string|false Returns the data read; returns false on failure. It also returns false, with an E_WARNING
     *                      level error thrown out, when method \Swoole\Process::useQueue() hasn't been called
     *                      successfully beforehand.
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Process::push()
     * @see \Swoole\Process::$id
     * @see https://www.man7.org/linux/man-pages/man2/msgrcv.2.html
     */
    public function pop(int $size = 65536): string|false
    {
    }

    /**
     * Terminates the process.
     *
     * This method can only be called in the process represented by the object. When called elsewhere (e.g., in the
     * parent process after method \Swoole\Process::start() is called), it does nothing except throwing out an E_WARNING
     * level error.
     *
     * @param int $exit_code The exit code of the process. It must be an integer in the range 0 to 255, otherwise an
     *                       E_WARNING level error is thrown out and the exit code is set to 1 implicitly.
     */
    public function exit(int $exit_code = 0): void
    {
    }

    /**
     * Replace the image of the current process with the given executable, through system call execv().
     *
     * On success, this method never returns: the current process keeps its process ID, but the PHP interpreter (its
     * memory, opened resources, registered callbacks, etc.) is replaced by the given program. Therefore, this method
     * returns a value only when it fails.
     *
     * @param string $exec_file Path of the executable file. It's passed to system call execv() as is, which means
     *                          environment variable PATH is not searched and thus an absolute path should be used.
     * @param array $args Arguments to be passed to the executable file. Each element is converted to string
     *                    implicitly. $exec_file itself is passed as the first argument (argv[0]) implicitly, and thus
     *                    should not be included in this array.
     * @return bool Returns false, with an E_WARNING level error thrown out, when the executable file can't be
     *              executed. Nothing is returned on success.
     */
    public function exec(string $exec_file, array $args): bool
    {
    }

    /**
     * Export the pipe of the process as a \Swoole\Coroutine\Socket object, so that data can be exchanged through the
     * pipe using the coroutine-friendly socket API.
     *
     * The Socket object wraps a duplicate of the underlying descriptor of the pipe, and the same Socket object is
     * returned every time this method is called on the same Process object.
     *
     * @return Socket|false Returns a \Swoole\Coroutine\Socket object on success; returns false on failure, with an
     *                      E_WARNING level error thrown out when the process doesn't have a pipe.
     * @see \Swoole\Process::$pipe
     * @see \Swoole\Coroutine\Socket
     */
    public function exportSocket(): Socket|false
    {
    }

    /**
     * Set the process name.
     *
     * There isn't a method in Swoole to get the process name. You can use PHP function \cli_get_process_title() to get the process name.
     *
     * @param string $process_name The new process name.
     * @return bool Returns true on success or false on failure.
     * @alias This method is an alias of function \swoole_set_process_name().
     * @see \swoole_set_process_name()
     * @see https://www.php.net/cli_set_process_title
     * @see https://www.php.net/cli_get_process_title
     * @pseudocode-included This is a built-in method in Swoole. The PHP code included inside this method is for explanation purpose only.
     */
    public function name(string $process_name): bool
    {
        if (PHP_SAPI !== 'cli') {
            // An E_WARNING level error will be thrown out here.
            return false;
        }

        return \cli_set_process_title($process_name);
    }

    /**
     * Wait for a child process of the current process to exit, and reap it.
     *
     * This static method waits for any child process of the calling process, not only the ones started through
     * \Swoole\Process objects. An exited child process stays in the system as a "zombie" process until it's reaped by
     * a call to this method. When child processes are managed asynchronously, register a handler for the SIGCHLD
     * signal (via method \Swoole\Process::signal()) and call this method inside it in non-blocking mode, in a loop,
     * until it returns false.
     *
     * @param bool $blocking Block until a child process exits (true, the default), or return false right away when no
     *                       child process has exited yet (false).
     * @return array|false Returns an array with the following three keys when a child process has exited:
     *                     - pid (int): Process ID of the exited child process.
     *                     - code (int): Exit code of the child process.
     *                     - signal (int): Number of the signal that killed the child process, or 0 when the child
     *                     process exited normally.
     *                     Returns false on failure, e.g., when the current process has no child process to wait for.
     * @see \Swoole\Process::signal()
     * @see https://www.man7.org/linux/man-pages/man2/waitpid.2.html
     */
    public static function wait(bool $blocking = true): array|false
    {
    }

    /**
     * Register (or remove) an asynchronous handler for a signal.
     *
     * The handler is executed through the event loop of the current process when the signal arrives; the event loop
     * is created implicitly if it doesn't exist yet. This method can be used in PHP CLI mode only; a fatal error is
     * triggered otherwise.
     *
     * @param int $signal_no The signal number, e.g., SIGTERM, SIGUSR1, or SIGCHLD.
     * @param callable|null $callback The callback function, called with the signal number as its only argument when
     *                                the signal arrives. When null is passed, the handler registered before for the
     *                                signal is removed instead. Constant SIG_IGN can also be passed in place of a
     *                                callback to make the process ignore the signal.
     * @return bool Returns true on success. It returns false, with an E_WARNING level error thrown out, when the
     *              signal number is invalid, when the signal is already handled internally by Swoole itself, or when
     *              null is passed but no handler has been registered for the signal.
     * @see \Swoole\Process::alarm()
     * @see \Swoole\Process::wait()
     * @see \Swoole\Process::kill()
     */
    public static function signal(int $signal_no, ?callable $callback = null): bool
    {
    }

    /**
     * Set (or cancel) an interval timer that delivers a signal to the current process periodically, through system
     * call setitimer().
     *
     * The signal delivered depends on parameter $type; use method \Swoole\Process::signal() to handle it. This
     * method can be used in PHP CLI mode only (a fatal error is triggered otherwise), and it can't be used together
     * with the timers of \Swoole\Timer: when timers exist in the current process, an E_WARNING level error is thrown
     * out and false is returned.
     *
     * @param int $usec Interval of the timer in microseconds. When 0 or a negative integer is passed, the timer is
     *                  cancelled.
     * @param int $type One of the following three values:
     *                  - 0 (the default; ITIMER_REAL): The timer counts down in real time. Signal SIGALRM is
     *                  delivered.
     *                  - 1 (ITIMER_VIRTUAL): The timer counts down only while the process is executing. Signal
     *                  SIGVTALRM is delivered.
     *                  - 2 (ITIMER_PROF): The timer counts down while the process is executing, and while the kernel
     *                  is working on behalf of the process. Signal SIGPROF is delivered.
     * @return bool Returns true on success or false on failure.
     * @see \Swoole\Process::signal()
     * @see \Swoole\Timer
     * @see https://www.man7.org/linux/man-pages/man2/setitimer.2.html
     */
    public static function alarm(int $usec, int $type = 0): bool
    {
    }

    /**
     * Send a signal to a process.
     *
     * When 0 is passed as the signal number, no signal is sent; the method just checks whether the target process
     * exists (and whether the current process is allowed to send signals to it), making it a handy way to test if a
     * process is still alive.
     *
     * @param int $pid Process ID of the target process.
     * @param int $signal_no The signal to send. Default to SIGTERM (15).
     * @return bool Returns true on success. It returns false, with an E_WARNING level error thrown out, when the
     *              signal can't be sent (the error is suppressed, though, when $signal_no is 0 and the target process
     *              simply doesn't exist).
     * @see \Swoole\Process::wait()
     * @see \Swoole\Process::signal()
     * @see https://www.man7.org/linux/man-pages/man2/kill.2.html
     */
    public static function kill(int $pid, int $signal_no = 15): bool
    {
    }

    /**
     * Turn the current process into a daemon, detached from the terminal and running in the background.
     *
     * Note that daemonizing involves a fork: the process that keeps running afterwards is a new process, with a
     * process ID different from the one the script started with.
     *
     * @param bool $nochdir Keep the current working directory unchanged (true, the default); when false is passed,
     *                      the working directory is changed to the root directory (/).
     * @param bool $noclose Keep the standard input, output, and error streams as they are (true, the default); when
     *                      false is passed, they are redirected to /dev/null.
     * @param array $pipes Streams, sockets, or file descriptors to install as the standard streams of the current
     *                     process before daemonizing: the first element replaces the standard input (file descriptor
     *                     0), the second the standard output (1), and the third the standard error (2). NULL elements
     *                     leave the corresponding descriptors unchanged, and elements beyond the third one are
     *                     ignored. To keep the replaced streams in effect, leave $noclose as true.
     * @return bool Returns true on success or false on failure.
     * @see https://www.man7.org/linux/man-pages/man3/daemon.3.html
     */
    public static function daemon(bool $nochdir = true, bool $noclose = true, array $pipes = []): bool
    {
    }

    /**
     * Set a process's CPU affinity mask.
     *
     * This method is available only on some operating systems that support CPU affinity. It's not available on Windows
     * or macOS.
     *
     * @param array<int> $cpu_settings
     * @return bool TRUE on success, or FALSE on failure.
     * @see https://linux.die.net/man/2/sched_setaffinity
     */
    public static function setAffinity(array $cpu_settings): bool
    {
    }

    /**
     * Get a process's CPU affinity mask.
     *
     * This method is available only on some operating systems that support CPU affinity. It's not available on Windows
     * or macOS.
     *
     * @return array<int> An array of integers representing the affinity mask of current process.
     * @see https://linux.die.net/man/2/sched_getaffinity
     */
    public static function getAffinity(): array
    {
    }
}
