<?php

declare(strict_types=1);

namespace Swoole;

use Swoole\Coroutine\Socket;

/**
 * @not-serializable Objects of this class cannot be serialized.
 */
class Process
{
    public const IPC_NOWAIT = 256;

    public const PIPE_MASTER = 1;

    public const PIPE_WORKER = 2;

    public const PIPE_READ = 3;

    public const PIPE_WRITE = 4;

    public int $pipe;

    /**
     * Identifier of the System V message queue used by the process, as returned by system call msgget().
     *
     * It's only set when method \Swoole\Process::useQueue() is called successfully.
     *
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Process::$msgQueueKey
     * @see https://www.man7.org/linux/man-pages/man2/msgget.2.html
     */
    public ?int $msgQueueId;

    /**
     * Key of the System V message queue used by the process, which is parameter $key passed to method
     * \Swoole\Process::useQueue(). When 0 or a negative integer is passed, the key generated by calling system call
     * ftok() on the PHP file where method \Swoole\Process::useQueue() is called is used instead; the "proj_id"
     * argument of ftok() (see ftok(3) below) is hardcoded to 1 in Swoole.
     *
     * It's only set when method \Swoole\Process::useQueue() is called successfully.
     *
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Process::$msgQueueId
     * @see https://www.man7.org/linux/man-pages/man3/ftok.3.html
     */
    public ?int $msgQueueKey;

    /**
     * Process ID. This is to uniquely identify the process in the OS.
     *
     * It's only set when the process represented by the object exists:
     *   - After method \Swoole\Process::start() is called successfully, it holds the process ID of the child process
     *     created, both in the parent process and in the child process itself.
     *   - For a process added to a server through method \Swoole\Server::addProcess(), it's set inside the user process
     *     itself when the process starts; it's not set in the process where method \Swoole\Server::addProcess() is
     *     called.
     *   - For an object returned by method \Swoole\Process\Pool::getProcess(), it holds the process ID of the
     *     corresponding worker process in the process pool.
     *
     * @readonly
     * @see \Swoole\Process::start()
     * @see \Swoole\Server::addProcess()
     * @see \Swoole\Process\Pool::getProcess()
     */
    public int $pid;

    /**
     * ID of the process.
     *
     * Unless one of the special cases described below applies, the ID is not coordinated across the running Swoole
     * program. It comes from a counter kept by (and private to) the PHP process in which the \Swoole\Process object is
     * created: the first object created in that process gets ID 1, and every object created afterwards gets the
     * previous ID plus one. If a \Swoole\Server has already been started in the current process by the time the first
     * \Swoole\Process object is created there, the counter starts from the total number of workers of the server (event
     * worker processes + task worker processes + user processes) instead of 1, so that the IDs don't clash with the IDs
     * of the server's own workers.
     *
     * The ID is assigned differently in the following cases:
     *   - When the object is created inside a worker thread of a running multi-threaded server (SWOOLE_THREAD mode), it
     *     represents one of the user processes of that server instead of a newly created process, and it takes the ID
     *     of that user process as is.
     *   - When the object is passed to method \Swoole\Server::addProcess(), that method overwrites the ID with the
     *     index of the user process among all the user processes added to the server (0 for the first one). Later on,
     *     when the server starts the user process, the ID is overwritten again, inside the user process, with the ID of
     *     the corresponding worker of the server (event worker processes and task worker processes counted in).
     *   - When the object comes from method \Swoole\Process\Pool::getProcess(), the ID is the ID of the worker process
     *     calling the method, which is not necessarily the ID of the worker process that the object represents.
     *
     * Therefore, the ID can be 0, e.g., right after an object is added to a server as the server's first user process,
     * or in the first worker process of a process pool.
     *
     * Besides identifying the process, the ID also determines the message type used by methods \Swoole\Process::push()
     * and \Swoole\Process::pop().
     *
     * @readonly
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Server::addProcess()
     * @see \Swoole\Process\Pool::getProcess()
     */
    public int $id;

    /**
     * @var callable The callback function of the process.
     */
    private $callback;

    /**
     * The constructor.
     *
     * @param callable $callback The callback function of the process.
     */
    public function __construct(callable $callback, bool $redirect_stdin_and_stdout = false, int $pipe_type = SOCK_DGRAM, bool $enable_coroutine = false)
    {
    }

    /**
     * Set process scheduling priority.
     *
     * Parameter $who is added in Swoole 5.0.2. Prior to this version, this method can only be used to set the priority
     * of the current process through method call $this->setPriority(PRIO_PROCESS, $priority).
     *
     * @param int $which One of the following three constants:
     *                   - PRIO_PROCESS: Set the priority of the process specified.
     *                   - PRIO_PGRP: Set the priority of all the processes in the process group specified.
     *                   - PRIO_USER: Set the priority of all the processes owned by the user specified.
     * @param int $priority The priority value. Lower priorities cause more favorable scheduling. The actual priority
     *                      range varies between systems. On Linux 1.3.43+, it's in the range -20 to 19.
     * @param int|null $who Interpreted relative to $which:
     *                      - PRIO_PROCESS: A process identifier.
     *                      - PRIO_PGRP: Process group identifier.
     *                      - PRIO_USER: An effective user ID.
     *                      This parameter can be ignored (or set to NULL) when $which is PRIO_PROCESS and $who
     *                      is $this->pid. In another word, the following two calls are equivalent:
     *                      - $this->setPriority(PRIO_PROCESS, $priority, $this->pid);
     *                      - $this->setPriority(PRIO_PROCESS, $priority);
     * @return bool Returns true on success or false on failure.
     * @see \Swoole\Process::getPriority()
     */
    public function setPriority(int $which, int $priority, ?int $who = null): bool
    {
    }

    /**
     * Get process scheduling priority.
     *
     * Parameter $who is added in Swoole 5.0.2. Prior to this version, this method can only be used to get the priority
     * of the current process through method call $this->getPriority(PRIO_PROCESS).
     *
     * @param int $which One of the three constants: PRIO_PROCESS, PRIO_PGRP, or PRIO_USER.
     * @param int|null $who Interpreted relative to $which:
     *                      - PRIO_PROCESS: A process identifier.
     *                      - PRIO_PGRP: Process group identifier.
     *                      - PRIO_USER: An effective user ID.
     *                      This parameter can be ignored (or set to NULL) when $which is PRIO_PROCESS and $who is
     *                      $this->pid. In another word, the following two calls are equivalent:
     *                      - $this->getPriority(PRIO_PROCESS, $this->pid);
     *                      - $this->getPriority(PRIO_PROCESS);
     * @return int|false The highest priority (lowest numerical value) enjoyed by any of the specified processes, or false on error.
     * @see \Swoole\Process::setPriority()
     */
    public function getPriority(int $which, ?int $who = null): int|false
    {
    }

    /**
     * Configure the process.
     *
     * @param array $settings Only one setting is supported: "enable_coroutine" (bool), which overrides parameter
     *                        $enable_coroutine passed to the constructor. It must be set before method
     *                        \Swoole\Process::start() is called. Any other element in the array is ignored silently.
     * @see \Swoole\Process::__construct()
     */
    public function set(array $settings): void
    {
    }

    /**
     * Set the read and write timeout on the pipe of the process.
     *
     * @param float $seconds The timeout in seconds. When 0 is passed, the timeout is disabled, which means read and
     *                       write operations on the pipe block until they are done.
     * @return bool Returns true on success or false on failure. It also returns false, with an E_WARNING level error
     *              thrown out, when the process doesn't have a pipe.
     * @see \Swoole\Process::setBlocking()
     */
    public function setTimeout(float $seconds): bool
    {
    }

    public function setBlocking(bool $blocking): void
    {
    }

    /**
     * Create (or get access to) a System V message queue, and use it to exchange data between the process and the
     * process where the Process object is created.
     *
     * Once this method is called successfully, properties $msgQueueId and $msgQueueKey are set accordingly.
     *
     * Every message in a System V message queue carries a positive integer called the message type (the "mtype" field
     * of the message passed to system call msgsnd(), and the "msgtyp" argument of system call msgrcv()), which allows a
     * reader to fetch messages selectively. Swoole uses ($this->id + 1) as the message type of the process; 1 is added
     * because a message type must be greater than 0, while $this->id can be 0.
     *
     * There are two modes of the message queue:
     *   - SWOOLE_MSGQUEUE_ORIENT (1): Method \Swoole\Process::pop() passes ($this->id + 1) as the "msgtyp" argument of
     *     system call msgrcv(), and thus only fetches messages of that message type from the queue.
     *   - SWOOLE_MSGQUEUE_BALANCE (2, the default): Method \Swoole\Process::pop() passes 0 as the "msgtyp" argument of
     *     system call msgrcv(), and thus fetches the first message in the queue, no matter what message type it is of.
     *
     * Either mode can be combined with constant \Swoole\Process::IPC_NOWAIT (256), e.g.,
     * SWOOLE_MSGQUEUE_BALANCE | \Swoole\Process::IPC_NOWAIT, to make the queue non-blocking. In that case, methods
     * \Swoole\Process::push() and \Swoole\Process::pop() return false immediately instead of blocking, when the queue
     * is full or empty.
     *
     * Please note that no matter which mode is used, messages pushed through method \Swoole\Process::push() always
     * carry message type ($this->id + 1).
     *
     * @param int $key Key of the message queue, which is passed to system call msgget() together with flag IPC_CREAT
     *                 and permissions 0666. When 0 or a negative integer is passed, the key generated by calling
     *                 system call ftok() on the PHP file where this method is called is used instead; the "proj_id"
     *                 argument of ftok() (see ftok(3) below) is hardcoded to 1 in Swoole.
     * @param int $mode Mode of the message queue, as described above.
     * @param int $capacity Maximum number of bytes allowed in the message queue (msg_qbytes). The system default is
     *                      used when a non-positive integer is passed.
     * @return bool Returns true on success or false on failure.
     * @see \Swoole\Process::$msgQueueId
     * @see \Swoole\Process::$msgQueueKey
     * @see \Swoole\Process::push()
     * @see \Swoole\Process::pop()
     * @see \Swoole\Process::statQueue()
     * @see \Swoole\Process::freeQueue()
     * @see https://www.man7.org/linux/man-pages/man3/ftok.3.html
     * @see https://www.man7.org/linux/man-pages/man2/msgget.2.html
     * @see https://www.man7.org/linux/man-pages/man2/msgsnd.2.html
     * @see https://www.man7.org/linux/man-pages/man2/msgrcv.2.html
     */
    public function useQueue(int $key = 0, int $mode = 2, int $capacity = -1): bool
    {
    }

    /**
     * Get statistics of the message queue used by the process.
     *
     * @return array{queue_num: int, queue_bytes: int}|false Returns an array containing the number of messages
     *                                                       currently in the queue ("queue_num") and the number of
     *                                                       bytes currently in the queue ("queue_bytes"); returns
     *                                                       false on failure.
     * @see \Swoole\Process::useQueue()
     */
    public function statQueue(): array|false
    {
    }

    /**
     * Destroy the message queue used by the process, and release all the resources (messages included) associated
     * with it.
     *
     * @return bool Returns true on success or false on failure.
     * @see \Swoole\Process::useQueue()
     */
    public function freeQueue(): bool
    {
    }

    public function start(): bool|int
    {
    }

    public function write(string $data): int|false
    {
    }

    /**
     * Close the pipe of the process, or shut down one direction of it.
     *
     * Parameter $which takes one of the following values:
     *   - \Swoole\Process::PIPE_READ (3): Shut down the reading direction of the pipe used by the current process,
     *     through system call shutdown(fd, SHUT_RD). The pipe itself is kept open.
     *   - \Swoole\Process::PIPE_WRITE (4): Shut down the writing direction of the pipe used by the current process,
     *     through system call shutdown(fd, SHUT_WR). The pipe itself is kept open.
     *   - \Swoole\Process::PIPE_MASTER (1): Close the master end of the pipe, which is the end used by the process
     *     where the Process object is created.
     *   - \Swoole\Process::PIPE_WORKER (2): Close the worker end of the pipe, which is the end used by the child
     *     process.
     *   - 0 (the default): Close both ends of the pipe and destroy the pipe.
     *
     * @param int $which One of the values described above.
     * @return bool Returns true on success or false on failure. It also returns false, with an E_WARNING level error
     *              thrown out, when the process doesn't have a pipe (or when the pipe has been destroyed already).
     * @see \Swoole\Process::exportSocket()
     */
    public function close(int $which = 0): bool
    {
    }

    public function read(int $size = 8192): string|false
    {
    }

    /**
     * Push data into the message queue created by method \Swoole\Process::useQueue().
     *
     * No matter which mode the queue is in, the message is always pushed with message type ($this->id + 1), i.e., the
     * "mtype" field of the message passed to system call msgsnd() is set to ($this->id + 1).
     *
     * @param string $data The data to push. It can't be empty, and its length must be less than 65536 bytes;
     *                     otherwise, false is returned with an E_WARNING level error thrown out.
     * @return bool Returns true on success or false on failure. It also returns false, with an E_WARNING level error
     *              thrown out, when method \Swoole\Process::useQueue() hasn't been called successfully beforehand.
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Process::pop()
     * @see \Swoole\Process::$id
     * @see https://www.man7.org/linux/man-pages/man2/msgsnd.2.html
     */
    public function push(string $data): bool
    {
    }

    /**
     * Fetch data from the message queue created by method \Swoole\Process::useQueue().
     *
     * Which message is fetched depends on the mode of the queue: in mode SWOOLE_MSGQUEUE_ORIENT, only messages of
     * message type ($this->id + 1) are fetched; in mode SWOOLE_MSGQUEUE_BALANCE (the default), the first message in the
     * queue is fetched, no matter what message type it is of.
     *
     * @param int $size Maximum number of bytes to read. When the value passed in is not in the range of 1 to 65536, it
     *                  is reset to 65536 implicitly.
     * @return string|false Returns the data read; returns false on failure. It also returns false, with an E_WARNING
     *                      level error thrown out, when method \Swoole\Process::useQueue() hasn't been called
     *                      successfully beforehand.
     * @see \Swoole\Process::useQueue()
     * @see \Swoole\Process::push()
     * @see \Swoole\Process::$id
     * @see https://www.man7.org/linux/man-pages/man2/msgrcv.2.html
     */
    public function pop(int $size = 65536): string|false
    {
    }

    /**
     * Terminates the process.
     *
     * This method can only be called in the process represented by the object. When called elsewhere (e.g., in the
     * parent process after method \Swoole\Process::start() is called), it does nothing except throwing out an E_WARNING
     * level error.
     *
     * @param int $exit_code The exit code of the process. It must be an integer in the range 0 to 255, otherwise an
     *                       E_WARNING level error is thrown out and the exit code is set to 1 implicitly.
     */
    public function exit(int $exit_code = 0): void
    {
    }

    /**
     * Replace the image of the current process with the given executable, through system call execv().
     *
     * On success, this method never returns: the current process keeps its process ID, but the PHP interpreter (its
     * memory, opened resources, registered callbacks, etc.) is replaced by the given program. Therefore, this method
     * returns a value only when it fails.
     *
     * @param string $exec_file Path of the executable file. It's passed to system call execv() as is, which means
     *                          environment variable PATH is not searched and thus an absolute path should be used.
     * @param array $args Arguments to be passed to the executable file. Each element is converted to string
     *                    implicitly. $exec_file itself is passed as the first argument (argv[0]) implicitly, and thus
     *                    should not be included in this array.
     * @return bool Returns false, with an E_WARNING level error thrown out, when the executable file can't be
     *              executed. Nothing is returned on success.
     */
    public function exec(string $exec_file, array $args): bool
    {
    }

    public function exportSocket(): Socket|false
    {
    }

    /**
     * Set the process name.
     *
     * There isn't a method in Swoole to get the process name. You can use PHP function \cli_get_process_title() to get the process name.
     *
     * @param string $process_name The new process name.
     * @return bool Returns true on success or false on failure.
     * @alias This method is an alias of function \swoole_set_process_name().
     * @see \swoole_set_process_name()
     * @see https://www.php.net/cli_set_process_title
     * @see https://www.php.net/cli_get_process_title
     * @pseudocode-included This is a built-in method in Swoole. The PHP code included inside this method is for explanation purpose only.
     */
    public function name(string $process_name): bool
    {
        if (PHP_SAPI !== 'cli') {
            // An E_WARNING level error will be thrown out here.
            return false;
        }

        return \cli_set_process_title($process_name);
    }

    public static function wait(bool $blocking = true): array|false
    {
    }

    public static function signal(int $signal_no, ?callable $callback = null): bool
    {
    }

    public static function alarm(int $usec, int $type = 0): bool
    {
    }

    public static function kill(int $pid, int $signal_no = 15): bool
    {
    }

    public static function daemon(bool $nochdir = true, bool $noclose = true, array $pipes = []): bool
    {
    }

    /**
     * Set a process's CPU affinity mask.
     *
     * This method is available only on some operating systems that support CPU affinity. It's not available on Windows
     * or macOS.
     *
     * @param array<int> $cpu_settings
     * @return bool TRUE on success, or FALSE on failure.
     * @see https://linux.die.net/man/2/sched_setaffinity
     */
    public static function setAffinity(array $cpu_settings): bool
    {
    }

    /**
     * Get a process's CPU affinity mask.
     *
     * This method is available only on some operating systems that support CPU affinity. It's not available on Windows
     * or macOS.
     *
     * @return array<int> An array of integers representing the affinity mask of current process.
     * @see https://linux.die.net/man/2/sched_getaffinity
     */
    public static function getAffinity(): array
    {
    }
}
